title: "Dabbu"
description: "Documentation for the Dabbu Knowledge Platform and its projects"

url: "https://dabbu-knowledge-platform.github.io"
baseurl: "/docs"

markdown: kramdown
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
